### ISSUE TITLE
docker healthcheck for db emits many log messages

### ISSUE THREAD

**Issue by jeffgoh** [RotherOSS/otobo-docker#101]
In my default docker install as per the instructions, I keep getting this error every 30 seconds:
```
2022-08-18T09:10:54.660415+08:00 redacted otobo_db_1[2520297]: 2022-08-18  1:10:54 27458 [Warning] Access denied for user 'mysql'@'10.x.x.x' (using password: NO)

```
otobo-base.yml there is this healthcheck - I think it needs the string "--password ${OTOBO_DB_ROOT_PASSWORD}"?

 ```
 46     healthcheck:
 47       test: mysqladmin ping -h db ping
```
According to the manpage for mysqladmin:

> ping
> 
> Check whether the server is available. The return status from [mysqladmin](https://dev.mysql.com/doc/refman/8.0/en/mysqladmin.html) is 0 if the server is running, 1 if it is not. This is 0 even in case of an error such as Access denied, because this means that the server is running but refused the connection, which is different from the server not running.
> 

The healthcheck works, but is currently spamming my logs.

**Comment by bschmalhofer** [comment]
Hi Jeff,
yes, the "Access denied" messages in the log of the db service is annoying. I'll add the credentials to the ping command in the next patch level releases of OTOBO. 
An alternative health check would using _/usr/local/bin/healthcheck.sh_ in the MariaDB container. But this script also requires credentials for avoiding the "Access denied" messages.

Best regards,
    Bernhard Schmalhofer

**Comment by bschmalhofer** [comment]
The PR is merged in both rel-10_0 and rel-10_1.
@jeffgoh , could you try updating your otobo-docker sandbox https://github.com/RotherOSS/otobo-docker/tree ?

**Comment by jeffgoh** [comment]
Wow - that was quick - I'm still digesting the OTRS to OTOBO migration docs and hadn't checked back here. Will get it done this weekend and update this ticket

**Comment by jeffgoh** [comment]
Actually, I was so motivated by the quick response by @bschmalhofer (and ashamed that my notifications don't seem to be working) that I did it after-hours today:

```
# docker-compose up --detach --build
otobo_redis_1 is up-to-date
Recreating otobo_db_1 ... 
Recreating otobo_db_1 ... done
otobo_web_1 is up-to-date
otobo_daemon_1 is up-to-date
# podman logs otobo_db_1
...
2022-08-23  9:43:35 0 [Note] mysqld: ready for connections.
Version: '10.5.16-MariaDB-1:10.5.16+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2022-08-23  9:43:35 0 [Note] InnoDB: Buffer pool(s) load completed at 220823  9:43:35
# date
Tue 23 Aug 2022 05:46:21 PM +08
```
So it's been two minutes (adjust 8 hours ... reminder to self - need to add timezone to each container) and no "Access denied", so I think can reasonably say the fix works!

**Comment by bschmalhofer** [comment]
Thanks!
