### ISSUE TITLE
MariaDB database container healthcheck script has issues with certain passwords

### ISSUE THREAD

**Issue by sjansen1** [RotherOSS/otobo-docker#103]
Hello,

today i updated OTOBO from 10.1.4 to 10.1.5 and my otobo-db-1 container fails healthcheck. After inspecting this container i found a lot of mysqladmin defunct proceses piling up on every healthcheck.

After inspecting the logs i found that there is a command not found error and that this command is part of the database password, it looks like the healthcheck script is not escaping correctly, i have certain special characters in the database password that may be the cause.

I solved it editing "docker-compose/otobo-base.yml" and changed "mysqladmin -h db --user=root --password=${OTOBO_DB_ROOT_PASSWORD} ping" with the real pasword in single quotes.

The healthcheck script for the database should be changed to quote whatever come with ${OTOBO_DB_ROOT_PASSWORD} variable.

**Comment by bschmalhofer** [comment]
Thanks for reporting this and for providing a fix. The password was added for #101, avoiding excessive log messages. I'll add the single quotes around the password.

**Comment by bschmalhofer** [comment]
@sjansen1 Could you update your _otobo-docker_ sandbox and check whether the fix works for you. 

I also suspect that the case where the password contains a single quote is not yet handled well.

**Comment by sjansen1** [comment]
@bschmalhofer i tested an update and a new installation, the healthcheck with "problematic" passwords works fine now.

**Comment by bschmalhofer** [comment]
@sjansen1 , thanks for the feedback!

Ignoring the issue with single quotes in the password for now. Closing this issue.
