### ISSUE TITLE
Healthchecks for OTOBO docker image

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo-docker#12]
Hi,

I think it's a good idea to define some health checks for our Otobo docker image. Example:

https://effective-docker.github.io/docker-healthchecks/

Another idea is to define the checks in our docker-compose file, that's, possible too!

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
Yes, that's a good idea.

**Comment by wornet-aer** [comment]
Is anyone working on this yet?
If not, I could offer implementing healthchecks using docker-compose and prepare a PR then.

**Comment by StefanRother-OTOBO** [comment]
Hi warnet-aer,

perfekt, thanks, you are welcome!

Thanks for your help!

Stefan

**Comment by bschmalhofer** [comment]
Health checks have been added, thaks to @wornet-aer . Let's keep this issue oben for a while, making sure that there are no adverse effects.

**Comment by bschmalhofer** [comment]
This looks good:

> bes:~/devel/OTOBO/otobo-docker (rel-10_0)$ docker-compose ps
>          Name                        Command                  State                                                  Ports                                           
> ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
> otobo_daemon_1            /opt/otobo_install/entrypo ...   Up (healthy)                                                                                              
> otobo_db_1                docker-entrypoint.sh --max ...   Up (healthy)   3306/tcp                                                                                   
> otobo_elastic_1           /bin/tini -- /usr/local/bi ...   Up (healthy)   9200/tcp, 9300/tcp                                                                         
> otobo_localstack_1        docker-entrypoint.sh             Up             0.0.0.0:4566->4566/tcp,:::4566->4566/tcp, 0.0.0.0:4571->4571/tcp,:::4571->4571/tcp,        
>                                                                           5678/tcp, 0.0.0.0:8080->8080/tcp,:::8080->8080/tcp                                         
> otobo_nginx_1             /docker-entrypoint.sh ngin ...   Up             80/tcp, 0.0.0.0:81->8080/tcp,:::81->8080/tcp, 0.0.0.0:443->8443/tcp,:::443->8443/tcp       
> otobo_redis_1             docker-entrypoint.sh redis ...   Up (healthy)   6379/tcp                                                                                   
> otobo_selenium-chrome_1   /opt/bin/entry_point.sh          Up             4444/tcp, 0.0.0.0:5900->5900/tcp,:::5900->5900/tcp                                         
> otobo_web_1               /opt/otobo_install/entrypo ...   Up (healthy) 

Before setup was completed the daemon process was on 'unhealthy', which was correct as the Daemon only runs in Secure mode. Finishing setup and restarting the service daemon brought it up to healthy.

**Comment by bschmalhofer** [comment]
TODO:

- [x] add a health check for Nginx

**Comment by wornet-aer** [comment]
I'm only running OTOBO instances without nginx here, but I will try to add some nginx health checks using a dev environment this week.

**Comment by bschmalhofer** [comment]
Thanks a lot, Andreas. 
The PR is merged. I'll leave this issue open for a couple of days, in case there are problems.

**Comment by bschmalhofer** [comment]
Never followed up by actually closing the issue. Closing now.

**Comment by bschmalhofer** [comment]
The health check for the service `web` is currently:

```
     healthcheck:
        test: curl -s -f http://localhost:5000/robots.txt
```
But `curl` has many different exit codes and the health check expects either 0 or 1. So let's change the command to :+1: 
   `curl -s -f http://localhost:5000/health` .

The route health has been added in https://github.com/RotherOSS/otobo/issues/1699.
