### ISSUE TITLE
Nginx redirect from http:// to https:// does not work 

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo-docker#2]
Nginx redirect from http:// to https:// does not work 

The redirect land on https://localhost

**Comment by bschmalhofer** [comment]
Looks better now. I tested this with:

- http://bernhard-hp-250-g6-notebook-pc/hello
- http://localhost/hello

@svenoe : Could you test whether this works for you as well?

**Comment by StefanRother-OTOBO** [comment]
Hi,

at our last customer, where we stay together in Munich (svo, bes, sr), it did not work. We need to check it again please.

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
Checked the redirect with the local-10.0.x, that is pre 10.0.4, images and it looked good. Closing the issue.
