### ISSUE TITLE
Changing HTTP port in .env does not work

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo-docker#21]
Hi,

I try to change the port inside the .env file:

```
OTOBO_DB_ROOT_PASSWORD=otobo_root
  
# set this var when the HTTP port is not 80
OTOBO_WEB_ROOT_HTTP_PORT=8080

# Elasticsearch options
OTOBO_ELASTICSEARCH_ES_JAVA_OPTS=-Xms512m -Xmx512m

COMPOSE_PROJECT_NAME=otobo
COMPOSE_PATH_SEPARATOR=:
COMPOSE_FILE=docker-compose/otobo-base.yml:docker-compose/otobo-override-http.yml
```

After starting docker-compose up -d the following error occurs:

```
Starting otobo_web_1     ... error

ERROR: for otobo_web_1  Cannot start service web: driver failed programming external connectivity on endpoint otobo_web_1 (20c165298f2508f8de26b7122398da16a13d1bf64f76af10e66dc5da6df448ed): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
```

Port 8080 is not used. 

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
The .env variables have been renamed to OTOBO_WEB_HTTP_PORT, OTOBO_WEB_HTTPS_PORT respectively. But the varible wasn't renamed in the commented out line in _.docker_compose_env_http_. The documentation looks fine.

**Comment by bschmalhofer** [comment]
The two sample .env files, for HTTP and HTTPS, have been enhanced. OTOBO_WEB_ROOT_HTTP_PORT is no longer mentioned. Closing this ticket.
