### ISSUE TITLE
MariaDB query cache size

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo-docker#30]
The support data collector reports:

Warning Größe Abfrage-Cache (1048576)

Die Einstellung query_cache_size sollte genutzt werden (mehr als 10 MB aber nicht mehr als 512 MB). 

So, the MariaDB query cache size should be configurable in _.env_
A normal setting is  33554432, so this should be the default.

**Comment by bschmalhofer** [comment]
See also https://mariadb.com/kb/en/query-cache/ . Looks like activating the query cache is a good idea.

**Comment by dwuensche-newtron** [comment]
I have created a pull request regarding this issue:
https://github.com/RotherOSS/otobo-docker/pull/68

**Comment by bschmalhofer** [comment]
Hi Daniel, @dwuensche-newtron,

thanks for your contribution, especially for double checking the effect. I have merged your PR and additionally added the new setting to the template file.   

Closing this issue.
