### ISSUE TITLE
Docker Hub: make the build faster

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo-docker#31]
Optimise the build time, especially on docker hub. 

Local builds take advantage of Docker layer caching. Therefore builds are fast when the required Debian packages and CPAN modules did not change. The subjective impression is that this does not apply for builds on Docker hub.

TODO:
- [ ] investigate whether Docker Hub takes advantage of layer caching
- [ ] if not, try to make Docker Hub do so
- [ ] as a fallback, create a base image with only the the dependencies and use that

**Comment by StefanRother-OTOBO** [comment]
Closed, builds now faster and in GitHub.
