### ISSUE TITLE
Avoid incomplete update

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/otobo-docker#34]
With versions set in `/opt/otobo-docker/.env` like this

```
OTOBO_IMAGE_OTOBO=rotheross/otobo:rel-10_0_4
OTOBO_IMAGE_OTOBO_ELASTICSEARCH=rotheross/otobo-elasticsearch:rel-10_0_4
OTOBO_IMAGE_OTOBO_NGINX=rotheross/otobo-nginx-webproxy:rel-10_0_4
```

it is possible to get an incomplete update to `rel-10_0_6`.

Symptoms:

```
/opt/otobo-docker# docker run -it --rm --volume otobo_opt_otobo:/opt/otobo rotheross/otobo:rel-10_0_6 copy_otobo_next
Unable to find image 'rotheross/otobo:rel-10_0_6' locally
rel-10_0_6: Pulling from rotheross/otobo

# entrypoint.sh is the old version without do_update_tasks()
root@ubuntu:/opt/otobo-docker# docker exec -t otobo_web_1 /opt/otobo_install/entrypoint.sh do_update_tasks
/opt/otobo_install/entrypoint.sh: line 44: exec: do_update_tasks: not found
```

In the case of `10.0.4` to `10.0.6` it results in a working installation, because there are no essential `do_update_tasks`.

Of course, commenting out the above settings in `/opt/otobo-docker/.env` and repeating the update solves the problem.

A possible improvement could be to check conflicts in version specifications and throw a warning or an error.

**Comment by bschmalhofer** [comment]
Hi @wollmers ,

yes, do_update_tasks() was added to _entrypoint.sh_ after OTOBO 10.0.4.  With regard to the updating process I have added a script for rotheross/otobo#567 . Could you check whether scripts/update.sh in the otobo-docker repository works for you. 
The process is not yet well documented. The gist is that you create a _env.m4_ template which will be converted to _.env_ 

Best regards,
   Bernhard

**Comment by wollmers** [comment]
Hi @bschmalhofer,

does it mean, that only updates of OTOBO <= 10.0.4 should run the script or should it work for versions >= 10.0.5 as well?

Seems `scripts/update.sh` is more for convenience. I can test it during this week.

**Comment by bschmalhofer** [comment]
_scripts/update.sh_ is meant for updates to OTOBO 10.0.7 or later. The dependency on do_update_tasks() could be removed, but I don't think that this is worth the hassle.

**Comment by wollmers** [comment]
The simple way

``
/opt/otobo-docker# ./scripts/update.sh
``

with `.env` edited works fine from OTOBO 10.0.6 to current git `rel-10_0 e67ede2`.

``
/opt/otobo-docker# otobo_docker_test_suite
``

passes, except TODOs and

``
not ok 770 - Kernel/System/UnitTest/Selenium.pm
``

**Comment by bschmalhofer** [comment]
The test failure is due to changes made for https://github.com/RotherOSS/otobo/issues/175. Will hopefully be fixed soon.

**Comment by wollmers** [comment]
IMHO Selenium tests should be skipped, if Selenium does not work (not properly configured or installed).

But the tests also are not working (non Docker installation, rel-10_0):

```
[21:27:44] /opt/otobo/scripts/test/Selenium/SysConfig/AgentSetting.t .. 1/? Undefined subroutine &main::done_testing
```
(I know the patch for it.)


And the tests need adaption, e.g.:

```
$Self->{'Loader::Agent::DefaultSelectedSkin'} =  'ivory';
```

Skin `ivory` is not available in OTOBO.

**Comment by bschmalhofer** [comment]
Let's close this old issue and open new issues when there are current problems with updating.
