### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by rkarlsba** [RotherOSS/otobo-docker#43]
Following the docs on https://doc.otobo.org/manual/installation/stable/en/content/installation-docker.html, I'm trying to install on debian buster, which fails with Unknown capability to add: "CAP_CAP_SYS_CHROOT" and "CAP_CAP_SETUID". Please see below for details. This looks like a typo, but I have no idea where to go to try to fix it. Can someone please help out?

root@otobo01:/opt/otobo-docker# docker-compose up --detach
WARNING: The NGINX_ENVSUBST_TEMPLATE_DIR variable is not set. Defaulting to a blank string.
Creating network "otobo_default" with the default driver
Creating volume "otobo_mariadb_data" with default driver
Creating volume "otobo_opt_otobo" with default driver
Creating volume "otobo_elasticsearch_data" with default driver
Creating volume "otobo_redis_data" with default driver
Pulling elastic (rotheross/otobo-elasticsearch:latest)...
latest: Pulling from rotheross/otobo-elasticsearch
75f829a71a1c: Pull complete
12a20a45aa50: Pull complete
7d49bb9ac613: Pull complete
98dcf7a2301a: Pull complete
26d68d841d2e: Pull complete
db71e2f6acdd: Pull complete
6d58f7bd0cd7: Pull complete
161752ba6659: Pull complete
8adf2f929b9e: Pull complete
042adb24e282: Pull complete
dac7e9e91c12: Pull complete
801c7fcdc0c0: Pull complete
Digest: sha256:00a979c112f235b5e56a02425a043d18d8fa20547fe8da56b103c0fe1a6914af
Status: Downloaded newer image for rotheross/otobo-elasticsearch:latest
Pulling db (mariadb:10.5.5)...
10.5.5: Pulling from library/mariadb
d72e567cc804: Pull complete
0f3630e5ff08: Pull complete
b6a83d81d1f4: Pull complete
4bf2111ecf0e: Pull complete
9572d64978a0: Pull complete
bcc9953bffb3: Pull complete
de429570dda5: Pull complete
3652bc6ea9f9: Pull complete
6e4bf87041c8: Pull complete
9cb9bba22391: Pull complete
9de10906fc5c: Pull complete
2c3a798c7a1f: Pull complete
Digest: sha256:9d27dd15564ba13a8ffa93beee20b39b7c14218c47ea296c6e11878a77962d12
Status: Downloaded newer image for mariadb:10.5.5
Pulling redis (redis:6.0.8-alpine)...
6.0.8-alpine: Pulling from library/redis
188c0c94c7c5: Pull complete
fb6015f7c791: Pull complete
f8890a096979: Pull complete
1ab9e54597f5: Pull complete
aea83659e879: Pull complete
75cca444dec7: Pull complete
Digest: sha256:eedaa0059551597b8205b0ab33e6f23ac2da2a507e24bcb53409e0538f74da0a
Status: Downloaded newer image for redis:6.0.8-alpine
Pulling web (rotheross/otobo:latest)...
latest: Pulling from rotheross/otobo
b9a857cbf04d: Pull complete
d557ee20540b: Pull complete
3b9ca4f00c2e: Pull complete
667fd949ed93: Pull complete
4ad46e8a18e5: Pull complete
5e397b98e2c3: Pull complete
44f83e053171: Pull complete
bdb1b2f4bbc0: Pull complete
fcf4d2d1bfe7: Pull complete
0b34260fd1ba: Pull complete
4a72cd5acc1c: Pull complete
ad6cfd48ad17: Pull complete
cb56050b5c8a: Pull complete
da0b93a6801e: Pull complete
1d41f4ab2022: Pull complete
9f85f710fb1f: Pull complete
1a8f0ad9d9cb: Pull complete
704ed2b732ba: Pull complete
efd7c7199dd0: Pull complete
a7e81ee55940: Pull complete
Digest: sha256:075b0bab8ee85d7f73646993e79cf4e217e62dc50bc88e35aa735293843d600c
Status: Downloaded newer image for rotheross/otobo:latest
Pulling nginx (rotheross/otobo-nginx-webproxy:latest)...
latest: Pulling from rotheross/otobo-nginx-webproxy
45b42c59be33: Pull complete
d0d9e9ea897e: Pull complete
66e650438339: Pull complete
76a3dfe4406b: Pull complete
410ff9d97480: Pull complete
f1a49221f4c5: Pull complete
5aa86c7d3316: Pull complete
08357f5e8d11: Pull complete
472f957ac40e: Pull complete
Digest: sha256:2b2b5dbf1492b0d0da45961b6dbcf38f4424d52eb7459feb9dd5819fa7c9490d
Status: Downloaded newer image for rotheross/otobo-nginx-webproxy:latest
Creating otobo_elastic_1 ... error
Creating otobo_redis_1   ...
Creating otobo_db_1      ...

Creating otobo_db_1      ... error
Creating otobo_redis_1   ... done
ERROR: for otobo_db_1  Cannot start service db: linux spec capabilities: Unknown capability to add: "CAP_CAP_SYS_CHROOT"

ERROR: for elastic  Cannot start service elastic: linux spec capabilities: Unknown capability to add: "CAP_CAP_SETUID"

ERROR: for db  Cannot start service db: linux spec capabilities: Unknown capability to add: "CAP_CAP_SYS_CHROOT"
ERROR: Encountered errors while bringing up the project.

**Comment by StefanRother-OTOBO** [comment]
Hi,

are you sure that you use newer versions like the minimum requirements?

Docker 19.03.13
Docker Compose 1.25.0

For me it looks like old docker-compose or docker version.

Best regards,

Stefan

**Comment by rkarlsba** [comment]
Looks to me I can only find docker-compose v1.25 from direct download, not a repo - is this correct? if so, how should I manage automatic updates?

**Comment by StefanRother-OTOBO** [comment]
Sorry, I don't know the Debian Buster repos in detail. Ubuntu 20.04 LTS brings a newer version for example.

To get the required minimal versions follow for example the instructions in https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-ubuntu-18-04 and https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04.

**Comment by StefanRother-OTOBO** [comment]
I found a repo for Debian buster: 

version 1.25.0-1 (main) [bullseye, sid]

**Comment by rkarlsba** [comment]
Mixing bullseye repo with stable, is very unwise. Mixing Sid repos with stable, is suicidal. Downloading directly from guthub as suggested here https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-debian-10 is obviously possible, but the package won't be upgraded regularly, which is important running servers over time. You don't want handcrafted or otherwise directly installed software. You want official packages.

**Comment by StefanRother-OTOBO** [comment]
The problem is, where do we start? In Fedora, Cent-OS and Red-Hat, there are older versions still included in the standard. In my opinion, it is also common practice that Docker Compose is better installed from sources, as the versions in the repos are often outdated. We were developing new software and therefore decided to use new versions.  Alternatively, you can adapt the Docker Compose file, I think the variables are the problem. If you set them directly, it could also work with the old version. Or you generate your own container.

You are also welcome to ask us to create suitable packages for you. A short e-mail to hello@otobo.de is enough. 

But this is not an issue, because we have clearly marked the minimal versions.

I ask for your understanding.

**Comment by rkarlsba** [comment]
I know you have clearly marked the minimal versions. It is, however, an issue that Otobo can't be installed cleanly on a vast majority of distros, just because you have used a bleeding-edge version.

**Comment by StefanRother-OTOBO** [comment]
Your welcome to help the OTOBO community to build a docker-compose file like that. OTOBO is 100% free and open source. Please help to improve.

**Comment by rkarlsba** [comment]
That's easy to say, but when I don't know my way around the guts of docker, that's not very easy.
