### ISSUE TITLE
Access denied when trying to initially connect

### ISSUE THREAD

**Issue by rkarlsba** [RotherOSS/otobo-docker#45]
After installing with new docker-compose, 1.28.2, on docker 20.10.3, all seems to work, but when I try to connect to the server in a web browser, I get this

An Error Occurred

Access denied for user 'otobo'@'172.19.0.5' (using password: YES)

I have set a root password in .env, otherwise, nothing special. Anything that should be done here? Can't find any clues in the docs.

**Comment by svenoe** [comment]
See https://github.com/RotherOSS/otobo/issues/802
