### ISSUE TITLE
Update Script cannot find container otobo_web_1

### ISSUE THREAD

**Issue by wornet-aer** [RotherOSS/otobo-docker#55]
When trying to update our otobo-docker instance using `./scripts/update.sh`, the following error message is shown:
```
sleeping for 10s, while the database is starting up
finished with sleeping
Error: No such container: otobo_web_1
Error: No such container: otobo_web_1
```

Since we are running an OTOBO dev and prod environment on the same docker host, the containers have another name.

After looking at the update script and reading the manual (https://doc.otobo.org/manual/installation/stable/de/content/updating-docker.html), it seems like the `docker exec` calls should be replaced by `docker-compose exec`.

Executing the commands from the docs manually with the correct container names can be used as a workaround.

**Comment by bschmalhofer** [comment]
Hi Andreas, @wornet-aer,

excellent, this looks good. I'll do a quick test tomorrow and then merge the pull request. 

Danke!

**Comment by bschmalhofer** [comment]
Tested by doing a downgrade from 10.1.x to 10.0.10. Looks fine.

The containername otobo_web_1 is also hardcoded in _scripts/devel/prepare_selenium_container.sh_. Let*s leave that for now, as we are thinking about having an OTOBO specific images for Selenium testing. In that case the script would be no longer needed.

The PR is merged. Thanks  @wornet-aer . Closing this issue.
