### ISSUE TITLE
Update versions of mariadb and redis in otobo-base.yml

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo-docker#65]
Currently _docker-compose/otobo-base.yml_ contains hardcoded patchlevel releases of the MariaDB and Redis images. It should be checked whether these images still receive security update.

**Comment by svenoe** [comment]
We changed this to minor upgrade level.

**Comment by bschmalhofer** [comment]
While discussing this, @svenoe and me found that allowing the users to set these versions via _.env_ would be a good idea. Let's do this in a separate issue.
