### ISSUE TITLE
Unable send or fetchmail

### ISSUE THREAD

**Issue by ghunmaster** [RotherOSS/otobo-docker#66]
Dear Dev

I try configuration email in otodo-docker but i got many error about email send and fetch
![image](https://user-images.githubusercontent.com/78137325/130185251-ca5e422d-c31f-4bc1-9fca-966b6bffbbc8.png)
![image](https://user-images.githubusercontent.com/78137325/130185354-c7d96cdf-8ffe-4e88-b90e-fee3ae1af66d.png)

**Comment by StefanRother-OTOBO** [comment]
Dear Ghunmaster,

that's for sure not a OTOBO bug. Please use SMTP, SMTPS or SMTPTLS for sending in a standard docker image. You find all required information at Admin -> Systemconfiguration and search "sendmail".

For your IMAP Config check Admin -> PostMaster Mail Accounts please. OTOBO can't connect to your IMAP Server.

If you have questions, please ask inside the OTOBO forum https://forum.otobo.org for help.

Best wishes,

Stefan
