### ISSUE TITLE
Error in script update.sh

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo-docker#70]
Hi,

as soon as several OTOBO environments are running on one server, the script update.sh does not work anymore, because there hardcoded the service "web" is called. 

But when I set up multiple environments, I give different names to the environments.
So we have to find out in the script first what the OTOBO container is called.

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
Hi Stefan, @StefanRother-OTOBO,

how did you rename the environment ? Did you rename the service 'web' in docker-compose/otobo-base.yml ?

The current approach is to use simple names like web or db for the services. The COMPOSE_PROJECT_NAME is set  in _.env_.  Per default the project name is set to to 'otobo' resulting in container names like 'otobo_web_1'. Wen set to 'acme' we get container names like 'acme_web_1'.

> bes:~/devel/OTOBO/redux/otobo-docker (rel-10_0)$ docker ps | grep web_1
> d8eb8aef0e0a   otobo:local-10.1.x                  "/opt/otobo_install/…"   4 minutes ago   Up 4 minutes                                                             acme_web_1
> 25f8db1cd1a5   otobo:local-10.1.x                  "/opt/otobo_install/…"   20 hours ago    Up About an hour                                                         otobo_web_1
>

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

ah ok I understood. I tried it before a view month like you described, but I'm not abled to setup multiple systems.
Are you sure that this work now? If yes I change my proceed.

Thanks!

Stefan

**Comment by bschmalhofer** [comment]
I just briefly tried that approach and it looked fine. There were some complaints about reused ports but that is to be expected. Did you seperated docker-compose directoried for each environment, that is for each project name?

**Comment by StefanRother-OTOBO** [comment]
Yes, I separate it. But thanks and no problem, I try this way out. In the meantime I change the upgrade script for the customer, where I use different service names.

Thanks!
