### ISSUE TITLE
Installation documentation link broken

### ISSUE THREAD

**Issue by KAVA-Leigh** [RotherOSS/otobo-docker#87]
Install guide not available from repo url

**Comment by bschmalhofer** [comment]
Hi @KAVA-Leigh ,

sorry for taking so long for that simple fix. I guess I need to check more often the open issues in this repository. 

I changed the documentation link to https://doc.otobo.org/, which is pretty much guaranteed to stay stable.

**Comment by bschmalhofer** [comment]
Checked the adapted README in rel-10_0 and rel-10_1. Closing this issue.
