### ISSUE TITLE
"OTOBO Daemon is not running." message when it is.

### ISSUE THREAD

**Issue by snk-nick** [RotherOSS/otobo-docker#96]
Getting the message that the Daemon is not running (rel-10_1) when it is definitely running. 

Checked status via `./otobo.Daemon.pl status` and it shows as working fine. Stopped/started it. Same thing. I can even see its status messages scrolling by in the console.

**Comment by bschmalhofer** [comment]
Hi @snk-nick,

I investigatedj how it it determined whether the Daemon is running.

The command `./bin/otobo.Daemon.pl status` reads the PID of the running Daemon from _/opt/otobo/var/run/Daemin-NodeID-1.pid_ and checks whether this process is running. This seems to work fine on your setup.

The notification relies on a different mechanism. The running Daemon continually writes in the cache that it is running. This message disappease after 30 s unless it is refreshed. The notification reports when this alive message is not longer available in the cache.

So one reason that the message is showing up, is that the communication via the cache might be broken. Could you check whether caching is activated, that is whether the config setting `Cache::InBackend` is active.

Best regards,
    Bernhard

**Comment by bschmalhofer** [comment]
There were no further reports about this problem. So, let's consider it to be solved.
