### ISSUE TITLE
Struggeling with LDAP

### ISSUE THREAD

**Issue by SteffenBernd** [RotherOSS/otobo-docker#98]
Hello,
im stuggeling to impliment LDAP with OTOBO.
i´ve installed OTOBO with the .docker_compose_env_http
Was that a misstake?
Greetings
Steffen

**Comment by bschmalhofer** [comment]
Hi Steffen,

in regard to LDAP support HTTP or HTTPS should make no difference. The web server is actually always only providing HTTP. HTTPS is provided via the SSL terminating Nginx proxy.
If you still have problems, then please ask at the OTOBO forum, https://otobo.de/en/forums/otobo/otobo-forum/.

Best regards,
   Bernhard
